name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Inject secrets
        env:
          WEB_CLIENT_ID: ${{ secrets.WEB_CLIENT_ID }}
          NAVER_CLIENT_ID: ${{ secrets.NAVER_CLIENT_ID }}
          NAVER_CLIENT_SECRET: ${{ secrets.NAVER_CLIENT_SECRET }}
          KAKAO_NATIVE_APP_KEY: ${{ secrets.KAKAO_NATIVE_APP_KEY }}
        run: |
          echo "WEB_CLIENT_ID=${WEB_CLIENT_ID}" >> local.properties
          echo "NAVER_CLIENT_ID=${NAVER_CLIENT_ID}" >> local.properties
          echo "NAVER_CLIENT_SECRET=${NAVER_CLIENT_SECRET}" >> local.properties
          echo "KAKAO_NATIVE_APP_KEY=${KAKAO_NATIVE_APP_KEY}" >> local.properties

      - name: Create google-services.json
        env:
          GOOGLE_SERVICES_JSON: ${{ secrets.GCP_SERVICES_JSON }}
        run: |
          echo "$GOOGLE_SERVICES_JSON" > app/google-services.json

      # Lint 실행 (정적 분석)
      - name: Run Lint
        run: ./gradlew lintDebug

      # 앱 빌드 (컴파일 검증)
      - name: Build with Gradle
        run: ./gradlew assembleDebug
